apiVersion: apps/v1
kind: Deployment
metadata:
  name: yankinttpf
  labels:
    app: yankinttpf
spec:
  replicas: 1
  selector:
    matchLabels:
      service: yankinttpf
  template:
    metadata:
      labels:
        app: yankinttpf
        service: yankinttpf
    spec:
      containers:
        - name: yankinttpf
          image: yankinttpf.azurecr.io/yankinttpf:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
              protocol: TCP
          env:
            - name: ASPNETCORE_URLS
              value: http://+:8083
            - name: WebApiBaseAddress
              value: http://webapi