apiVersion: v1
kind: Service
metadata:
  name: yankinttpf
  labels:
    app: yankinttpf
    service: yankinttpf
spec:
  type: LoadBalancer
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
  selector:
    service: yankinttpf